//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime returnDate { get; set; }
        public Nullable<System.DateTime> actualReturnDate { get; set; }
        public int userId { get; set; }
        public int carId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
